- name: Add the repository for MySql 5.7
  become: true
  command: add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'

- name: Update
  become: true
  command: apt-get update

- name: Install mysql
  become: true
  apt: pkg={{ item }} state=installed
  with_items:    
    - mysql-server-5.7
    - mysql-client-5.7
    - python-mysqldb
    - libmysqlclient-dev

- name: ensure mysql started
  become: true
  service: name=mysql state=started enabled=yes

- name: Update MySQL root password for all root accounts
  become: true
  mysql_user: 
    login_user: root 
    login_password: admin
    check_implicit_admin: yes 
    name: root
    host: "{{ item }}"
    password: admin
    state: present
  with_items:
    - 192.168.196.50
    - 127.0.0.1
    - ::1
    - localhost

- name: Create a new database
  mysql_db: name=demo state=present collation=utf8_general_ci

- name: 4. Create a database user
  mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present

- name: 5a. Copy sample data
  copy: src=/home/alin/Ansible/ansible-lamp-stack-playbook/roles/mysql/files/dump.sql dest=/tmp/dump.sql

- name: 5b. Insert sample data
  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

- name: ensure mysql started
  become: true
  service: name=mysql state=started enabled=yes
